# Use an official Go runtime as a parent image
FROM golang:1.15

# Set the working directory inside the container
WORKDIR /app

# Copy the local package files to the container's workspace
COPY . .

# Build the Go application
RUN go build -o main .

# Run the Go application
CMD ["./main"]

# Setting ENV variables
