version: "1.0"
services:
  redis:
    image: redis
    volumes:
      - /path/to/redis/data:/data

  app:
    build:
      context: .
    environment:
      DEMO_REDIS_ADDR: redis:6379
      DEMO_APP_ADDR: ":8080"
    depends_on:
      - redis

  nginx:
    image: nginx
    ports:
      - "80:80"
    links:
      - app
    volumes:
      - /path/to/nginx/config:/etc/nginx/conf.d
