---
- name: Provision VM with Ansible
  hosts: all
  become: yes

  tasks:
    - name: Set hostname to demo-ops
      hostname:
        name: demo-ops
      become: yes

    - name: Create a user named 'demo'
      user:
        name: demo
        shell: /bin/bash
      become: yes

    - name: Harden security - Disable root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
      become: yes

    - name: Configure basic firewall (UFW)
      apt:
        name: ufw
        state: present
      become: yes

    - name: Allow SSH through the firewall
      ufw:
        rule: allow
        name: OpenSSH
      become: yes

    - name: Enable the firewall
      ufw:
        state: enabled
      become: yes

    - name: Configure sysctl for sane defaults
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        sysctl_set: yes
      with_items:
        - { name: "fs.file-max", value: 65535 }
        - { name: "vm.swappiness", value: 10 }
      become: yes

      # Explanation: We increase the maximum number of open files allowed on the system to 65535. 
      # This is important for applications that require a large number of open file descriptors, such as web servers and databases. 
      # Increasing this limit helps prevent "Too many open files" errors and improves the performance of applications that use many files or network connections.

      # Swappiness controls the tendency of the kernel to move processes out of physical memory (RAM) and onto the swap space (disk). 
      # A lower value (e.g., 10) reduces the aggressiveness of swapping, which is beneficial for systems with ample RAM. 
      # It helps keep more data in RAM, improving overall system performance by minimizing disk I/O.

      # These changes aim to strike a balance between resource utilization and system performance. 
      # Increasing the open files limit accommodates applications that need many file descriptors, while adjusting swappiness helps maintain optimal RAM usage. 
      # These values should be adjusted based on the specific requirements of your system and the applications running on it

    - name: Set the system timezone to Asia/Kolkata
      timezone:
        name: Asia/Kolkata
      become: yes

    - name: Install Docker and Docker-Compose
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - docker.io
        - docker-compose
      become: yes

    - name: Configure Docker Daemon - Example: Set log size limit
      lineinfile:
        path: /etc/docker/daemon.json
        create: yes
        line: '{"log-driver": "json-file", "log-opts": {"max-size": "10m", "max-file": "3"}}'
      become: yes

    - name: Deploy docker-compose.yml to /etc/demo-ops
      copy:
        src: /path/to/your/docker-compose.yml
        dest: /etc/demo-ops/docker-compose.yml
      become: yes

    - name: Start the Docker services
      command: docker-compose -f /etc/demo-ops/docker-compose.yml up -d
      become: yes



## Execute the below command on CLI to run `provision.yml` file
# ansible-playbook -i vagrant@127.0.0.1, -e ansible_python_interpreter=/usr/bin/python3 provision.yml